version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    networks:
      testenv: {}
  app:
    image: golang:alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/testdb?sslmode=disable
    restart: on-failure
    networks:
      testenv: {}
networks:
  testenv:
    external: true
    name: testenv