version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=testdb
    networks:
      - go-auth-paseto
  go-auth-paseto:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/testdb?sslmode=disable
    depends_on:
      - postgres
    entrypoint:
      [
        "postgres:5432",
        "--",
      ]
    command: [ "/build/go-auth-paseto" ]
    networks:
      - go-auth-paseto